import 'package:dart_prism/dart_prism.dart' as p;
import 'package:flutter/painting.dart';

class PrismStyle extends p.PrismStyle<TextStyle> {
  PrismStyle({
    TextStyle? token,
    TextStyle? atrule,
    TextStyle? attrName,
    TextStyle? attrValue,
    TextStyle? bold,
    TextStyle? boolean,
    TextStyle? builtin,
    TextStyle? cdata,
    TextStyle? char,
    TextStyle? className,
    TextStyle? comment,
    TextStyle? constant,
    TextStyle? deleted,
    TextStyle? doctype,
    TextStyle? entity,
    TextStyle? function,
    TextStyle? important,
    TextStyle? inserted,
    TextStyle? italic,
    TextStyle? keyword,
    TextStyle? namespace,
    TextStyle? number,
    TextStyle? operator,
    TextStyle? prolog,
    TextStyle? property,
    TextStyle? punctuation,
    TextStyle? regex,
    TextStyle? selector,
    TextStyle? string,
    TextStyle? symbol,
    TextStyle? tag,
    TextStyle? url,
  }) : super(
          token: const TextStyle(color: Color(0xff90a4ae)).merge(token),
          atrule: const TextStyle(color: Color(0xff0000fa)).merge(atrule),
          attrName: const TextStyle(color: Color(0xff39adb5)).merge(attrName),
          attrValue: const TextStyle(color: Color(0xfff6a434)).merge(attrValue),
          bold: const TextStyle(fontWeight: FontWeight.bold).merge(bold),
          boolean: const TextStyle(color: Color(0xff0000fa)).merge(boolean),
          builtin: const TextStyle(color: Color(0xff39adb5)).merge(builtin),
          cdata: const TextStyle(color: Color(0xff39adb5)).merge(cdata),
          char: const TextStyle(color: Color(0xff39adb5)).merge(char),
          className: const TextStyle(color: Color(0xff6182b8)).merge(className),
          comment: const TextStyle(color: Color(0xff989898)).merge(comment),
          constant: const TextStyle(color: Color(0xff0000fa)).merge(constant),
          deleted: const TextStyle(color: Color(0xffe53935)).merge(deleted),
          doctype: const TextStyle(color: Color(0xff989898)).merge(doctype),
          entity: const TextStyle(color: Color(0xffe53935)).merge(entity),
          function: const TextStyle(color: Color(0xff766334)).merge(function),
          important: const TextStyle(
            color: Color(0xff0000fa),
            fontWeight: FontWeight.bold,
          ).merge(important),
          inserted: const TextStyle(color: Color(0xff39adb5)).merge(inserted),
          italic: const TextStyle(fontStyle: FontStyle.italic).merge(italic),
          keyword: const TextStyle(color: Color(0xff0000fa)).merge(keyword),
          namespace: const TextStyle(color: Color(0xb3000000)).merge(namespace),
          number: const TextStyle(color: Color(0xff4C855B)).merge(number),
          operator: const TextStyle(color: Color(0xff39adb5)).merge(operator),
          prolog: const TextStyle(color: Color(0xff989898)).merge(prolog),
          property: const TextStyle(color: Color(0xff39adb5)).merge(property),
          punctuation: const TextStyle(
            color: Color(0xff39adb5),
          ).merge(punctuation),
          regex: const TextStyle(color: Color(0xff6182b8)).merge(regex),
          selector: const TextStyle(color: Color(0xffe53935)).merge(selector),
          string: const TextStyle(color: Color(0xff8b1c1c)).merge(string),
          symbol: const TextStyle(color: Color(0xff0000fa)).merge(symbol),
          tag: const TextStyle(color: Color(0xffe53935)).merge(tag),
          url: const TextStyle(color: Color(0xffe53935)).merge(url),
        );
}
